### ISSUE TITLE
Readme Images

### ISSUE THREAD

**Issue by omkarSw2** [Rinkesh375/flying-word-4664#20]
![homeCurosel](https://github.com/Rinkesh375/flying-word-4664/assets/119350956/9d07bc99-9fbb-45b4-9aef-bf749d186dea)
![HomeRecent](https://github.com/Rinkesh375/flying-word-4664/assets/119350956/9892c7a3-2979-4d2e-ab02-40a191789584)
![HomeFooter](https://github.com/Rinkesh375/flying-word-4664/assets/119350956/9f27e474-2405-48d5-bf27-e6206ae129fb)
![ProductSection](https://github.com/Rinkesh375/flying-word-4664/assets/119350956/6e56d547-e816-4658-92d9-8acea1ef323c)
![ResponsiveDesktop](https://github.com/Rinkesh375/flying-word-4664/assets/119350956/e8d61b7b-7367-43de-843
![RespociveMobile](https://github.com/Rinkesh375/flying-word-4664/assets/119350956/171cd0fe-589a-41f8-8664-7858f4247376)

![ResposciveTablet](https://github.com/Rinkesh375/flying-word-4664/assets/119350956/420d9679-458d-4aa4-b94f-5bc0ee00413e)

![AdminPage](https://github.com/Rinkesh375/flying-word-4664/assets/119350956/b0e903c6-32ca-44ab-ba02-06345bd4d5c3)

![AdminLogin](https://github.com/Rinkesh375/flying-word-4664/assets/119350956/01e87533-a545-48fb-93e0-c0c52e694496)
-bb1398eda130)

**Comment by Rinkesh375** [comment]
done
